import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/ui/Navbar";
import { MantineProvider, ColorSchemeScript } from "@mantine/core";

// Fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Layout
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark" data-mantine-color-scheme="dark">
      <head>
        <ColorSchemeScript defaultColorScheme="dark" />
      </head>
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#0A0118] text-white`}
        style={{
          background: "linear-gradient(135deg, #0A0118 0%, #1A142F 100%)",
        }}
      >
        <MantineProvider withGlobalStyles withNormalizeCSS theme={{ colorScheme: "dark" }}>
          <Navbar />
          <main className="relative z-10">{children}</main>

          {/* Floating Mesh Backgrounds */}
          <div className="pointer-events-none fixed inset-0 z-0 overflow-hidden">
            <div className="absolute w-[40%] h-[50%] bg-[radial-gradient(circle,rgba(132,79,255,0.15)_0%,transparent_70%)] top-[-15%] left-[-10%] blur-[80px] animate-float" />
            <div className="absolute w-[50%] h-[60%] bg-[radial-gradient(circle,rgba(255,47,237,0.1)_0%,transparent_70%)] bottom-[-20%] right-[-5%] blur-[80px] animate-float-reverse" />
            <div className="absolute w-[40%] h-[40%] bg-[radial-gradient(circle,rgba(74,159,255,0.15)_0%,transparent_70%)] top-[30%] right-[-20%] blur-[80px] animate-float" />
          </div>
        </MantineProvider>
      </body>
    </html>
  );
}
